---
- name: Optimize Deployment
  hosts: all
  gather_facts: yes

  tasks:
    - name: Install Nginx 
      apt:
        name: nginx
        state: present
      become: yes

    - name: Wait for nginx to be installed
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: async_results
      until: async_results.finished
      retries: 30
      delay: 10
      with_items:
        - "{{ ansible_job_ids }}"
      when: async_results.ansible_job_id is defined
    - name: Ensure /var/www/html exists
      file:
        path: /var/www/html
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      become: yes
    - name: Configure Nginx
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
 